import { AlertTriangle, Thermometer, Wind, Info } from 'lucide-react';

const TYPE_META = {
  SST_HIGH:  { label: 'SST High',    accent: 'red',   icon: Thermometer, desc: 'Sea surface temperature above 30.5°C' },
  SST_LOW:   { label: 'SST Low',     accent: 'ocean', icon: Thermometer, desc: 'Sea surface temperature below 27.5°C' },
  WEATHER:   { label: 'Weather',     accent: 'amber', icon: Wind,        desc: 'High wave or wind conditions' },
  VESSEL:    { label: 'Vessel',      accent: 'red',   icon: AlertTriangle, desc: 'Vessel in protected zone' },
};

function timeAgo(ts) {
  const diff = (Date.now() - new Date(ts)) / 1000;
  if (diff < 60)   return `${Math.floor(diff)}s ago`;
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  return `${Math.floor(diff / 3600)}h ago`;
}

export default function Alerts({ data }) {
  if (!data) return null;
  const { alerts } = data;

  return (
    <div className="container" style={{ paddingTop: 32, paddingBottom: 48 }}>
      <div style={{ marginBottom: 28 }}>
        <div style={{ fontFamily: 'Playfair Display, serif', fontSize: 26, fontWeight: 700, color: 'var(--text)' }}>
          System Alerts
        </div>
        <div style={{ fontSize: 13, color: 'var(--text3)', marginTop: 4 }}>
          Generated by Cloud Functions fn1 (SST Anomaly Checker) and fn3 (Vessel Violation Detector)
        </div>
      </div>

      

      {alerts.length === 0 ? (
        <div className="card" style={{ padding: 48, textAlign: 'center' }}>
          <div style={{ fontSize: 32, marginBottom: 12 }}>✓</div>
          <div style={{ fontSize: 16, fontWeight: 600, color: 'var(--green)', marginBottom: 4 }}>All Systems Normal</div>
          <div style={{ fontSize: 13, color: 'var(--text3)' }}>No active alerts. All buoys reporting normal conditions.</div>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {alerts.map((a, i) => {
            const meta = TYPE_META[a.alert_type] || TYPE_META.WEATHER;
            const Icon = meta.icon;
            return (
              <div
                key={i}
                className="card fade-up"
                style={{
                  animationDelay: `${i * 40}ms`,
                  padding: 0, overflow: 'hidden',
                  borderLeft: `4px solid var(--${meta.accent})`,
                }}
              >
                <div style={{ padding: '16px 20px' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10 }}>
                    <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
                      <div style={{
                        width: 34, height: 34, borderRadius: 8, flexShrink: 0,
                        background: `var(--${meta.accent}2)`,
                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                      }}>
                        <Icon size={16} color={`var(--${meta.accent})`} />
                      </div>
                      <div>
                        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                          <span className={`badge badge-${meta.accent}`}>{meta.label}</span>
                          <span style={{ fontSize: 14, fontWeight: 600, color: 'var(--text)' }}>{a.zone_id}</span>
                        </div>
                        <div style={{ fontSize: 11, color: 'var(--text3)', marginTop: 2 }}>{meta.desc}</div>
                      </div>
                    </div>
                    <span style={{ fontSize: 11, color: 'var(--text3)', fontFamily: 'DM Mono, monospace', flexShrink: 0 }}>
                      {a.timestamp ? timeAgo(a.timestamp) : '—'}
                    </span>
                  </div>
                  <div style={{ fontSize: 13, color: 'var(--text2)', lineHeight: 1.5, marginLeft: 44 }}>
                    {a.message_en}
                  </div>
                  {a.sst_celsius > 0 && (
                    <div style={{ marginLeft: 44, marginTop: 8 }}>
                      <span style={{ fontSize: 11, color: 'var(--text3)', fontFamily: 'DM Mono, monospace' }}>
                        SST: {a.sst_celsius}°C · {a.lat}°N, {a.lon}°E
                      </span>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
